Repository Allen-Synthesis/EuroPi, pull requests merged in 2024-02, with the labels that each got.

#324 Consequencer jan 24
  software/contrib/consequencer.md
  software/contrib/consequencer.py
Labels: suggestion, new script feature

#332 Remove unexpected indent to fix doc build error
  software/firmware/europi.py
Labels: firmware, documentation

#329 Improvements to oled.centre_text()
  software/firmware/europi.py
Labels: firmware

#312 Use the new screensaver class in Pam's, Logic, and Euclid scripts
  software/contrib/euclid.py
  software/contrib/kompari.py
  software/contrib/logic.py
  software/contrib/pams.py
Labels: new script feature

#331 Add gate voltage to config
  software/CONFIGURATION.md
  software/firmware/europi.py
  software/firmware/europi_config.py
Labels: firmware

#313 Add Conway's Game of Life LFO
  software/contrib/README.md
  software/contrib/conway.md
  software/contrib/conway.py
  software/contrib/menu.py
  software/firmware/experimental/bitarray.py
Labels: new script

#314 Add Load/Save feature to Pam's
  software/contrib/pams.md
  software/contrib/pams.py
Labels: new script feature

#311 Add Traffic script
  software/contrib/README.md
  software/contrib/menu.py
  software/contrib/traffic.md
  software/contrib/traffic.py
  software/firmware/experimental/a_to_d.py
  software/firmware/experimental/screensaver.py
Labels: new script

#319 Add Clock Multiplier & Divider
  software/contrib/README.md
  software/contrib/clock_mod.md
  software/contrib/clock_mod.py
  software/contrib/menu.py
Labels: new script

#333 Remove USB workaround
  software/contrib/menu.py
Labels: firmware

#334 Convert to UNIX EOL
  software/uf2_build/copy_and_compile.sh
Labels: firmware

#347 Add Mouser links to BOM
  hardware/EuroPi/bill_of_materials.md
Labels: documentation, hardware - EuroPi
