Repository Allen-Synthesis/EuroPi, pull requests merged in 2024-06, with the labels that each got.

#363 Reduce latency in Clock Modifer script
  software/contrib/clock_mod.md
  software/contrib/clock_mod.py
  software/firmware/experimental/screensaver.py
Labels: improvement

#360 Bit Garden - Deterministic psudo random gate processor
  software/contrib/bit_garden.md
  software/contrib/bit_garden.py
  software/contrib/menu.py
  software/firmware/experimental/custom_font.md
  software/firmware/experimental/fonts/freesans14.py
  software/firmware/experimental/fonts/freesans17.py
  software/firmware/experimental/fonts/freesans20.py
  software/firmware/experimental/fonts/freesans24.py
  software/firmware/experimental/fonts/ubuntu.LICENSE
  software/firmware/experimental/fonts/ubuntumono14.py
  software/firmware/experimental/fonts/ubuntumono17.py
  software/firmware/experimental/fonts/ubuntumono20.py
  software/firmware/experimental/fonts/ubuntumono24.py
Labels: firmware, new script

#364 Improve responsiveness of Gates & Triggers
  software/contrib/gates_and_triggers.md
  software/contrib/gates_and_triggers.py
  software/firmware/experimental/knobs.py
  software/firmware/experimental/math.py
Labels: improvement

#366 Add sustain gate, end-of-rise, end-of-fall triggers to Envelope Generator
  software/contrib/envelope_generator.md
  software/contrib/envelope_generator.py
Labels: new script feature, improvement
